### ISSUE TITLE
the code  not support unordered triangles index

### ISSUE THREAD

**Issue by XuankeShi** [yig/halfedge#1]
you can try the data：
std::vector<float> ver = {
        -0.5f, 1.f,  0.f, 
        0.5f,  1.f,  0.f, 
        1.f,   0.f,  0.f,
        0.5f,  -1.f, 0.f,
        -0.5f, -1.f, 0.f,
        -1.f,  0.f,  0.f, 
        0.f,   0.f,  0.f   
    };
std::vector<int> tri = {
        1, 2, 7, 
        7, 2 ,3, 
        3, 4, 7, 
        7, 4, 5, 
        7, 5, 6, 
        7, 6, 1
    };

**Comment by yig** [comment]
The indices in the `tri` vector should be 0-based so they can be used to index into the vertex data `ver`. The numbers should be in the range [0,6]. The indices in your `tri` run from [1,7].
